#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>
#include "kitaevChain.h"
#include "pfqmc.h"
#include "projector_contour.h"
#include "projector_json.h"
#include "projector_mp_z2_oracle.h"

namespace {
struct Args{int L,boundary,hs,seed,burn,measurements,threads,diagnostic_stride,sign_stride,mp_spot_stride;double theta,beta,dt,V,delta,mu;std::string csv,legacy_csv;};
Args parse(int n,char**v){if(n!=18&&n!=19)throw std::runtime_error("usage: real_z2 L theta beta dt V delta mu boundary hs seed burn measurements threads comparison.csv diagnostic_stride sign_stride legacy.csv [mp_spot_stride]");Args a{std::stoi(v[1]),std::stoi(v[8]),std::stoi(v[9]),std::stoi(v[10]),std::stoi(v[11]),std::stoi(v[12]),std::stoi(v[13]),std::stoi(v[15]),std::stoi(v[16]),n==19?std::stoi(v[18]):std::stoi(v[15]),std::stod(v[2]),std::stod(v[3]),std::stod(v[4]),std::stod(v[5]),std::stod(v[6]),std::stod(v[7]),v[14],v[17]};if(a.L<2||a.theta<=0||a.beta<=0||a.dt<=0||a.V<0||a.burn<0||a.measurements<=0||a.threads!=1||a.sign_stride<=0||a.diagnostic_stride<0||a.mp_spot_stride<0)throw std::runtime_error("invalid arguments");return a;}
class Walker:public Spinless_tV{public:int center=-1,ntrial=0,nphys=0;Walker(const SpinlessTvChainUtils*c,rdGenerator*r,double t,double b){build_projector_static_contour(*this,c,r,t,b,center,ntrial,nphys);}};
std::vector<int> fields(const Spinless_tV&w){std::vector<int>x;for(Operator*o:w.op_array)if(auto*s=o->getAuxField())for(int i=0;i<s->size();++i)x.push_back((*s)(i));return x;}
long long changes(const std::vector<int>&a,const std::vector<int>&b){if(a.size()!=b.size())throw std::runtime_error("HS count changed");long long n=0;for(size_t i=0;i<a.size();++i)n+=a[i]!=b[i];return n;}
std::uint64_t hsHash(const Spinless_tV&w){std::uint64_t h=1469598103934665603ULL;for(int x:fields(w)){h^=std::uint64_t(std::int64_t(x));h*=1099511628211ULL;}return h;}
std::uint64_t mix(std::uint64_t h,std::uint64_t x){for(int i=0;i<8;++i){h^=(x>>(8*i))&255;h*=1099511628211ULL;}return h;}
double sem(const std::vector<double>&x){if(x.size()<2)return 0;double m=0,q=0;for(double v:x)m+=v;m/=x.size();for(double v:x)q+=(v-m)*(v-m);return std::sqrt(q/(x.size()*(x.size()-1)));}
}

int main(int argc,char**argv)try{
 const Args a=parse(argc,argv);mkl_set_num_threads(1);resetScaleSafeQRGuardDiagnostics();const int ns=2*int(std::llround(a.theta/a.dt));
 SpinlessTvChainUtils c0(a.L,a.dt,a.V,ns,a.boundary,a.delta,a.mu,a.hs),c1(a.L,a.dt,a.V,ns,a.boundary,a.delta,a.mu,a.hs);rdGenerator r0(a.seed),r1(a.seed);Walker w0(&c0,&r0,a.theta,a.beta),w1(&c1,&r1,a.theta,a.beta);
 PfQMC legacy(&w0,10);auto oracle=[](const std::vector<Operator*>&ops){return projector_mp_z2::fullContourZ2(ops);};const auto initStarted=std::chrono::steady_clock::now();PfQMC q(&w1,10,PfQMCSignMode::real_z2,oracle);const double realZ2InitializationSeconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-initStarted).count();legacy.configureAdaptiveGuard(false,.1,100);q.configureAdaptiveGuard(false,.1,100);legacy.configureLeftSweepGreenRecovery(false);q.configureLeftSweepGreenRecovery(false);
 const PfaffianResult initialRaw=q.getSignRawWithStatus();const int initialZ2=q.physicalZ2Sign();bool shadow=true;std::uint64_t trajectory=1469598103934665603ULL;auto audit=[&](){bool ok=hsHash(w0)==hsHash(w1)&&r0.diagnosticStateHash()==r1.diagnosticStateHash();shadow=shadow&&ok;trajectory=mix(mix(trajectory,hsHash(w1)),r1.diagnosticStateHash());};audit();
 auto started=std::chrono::steady_clock::now();double legacyKernelSeconds=0,realZ2KernelSeconds=0;auto timeLegacy=[&](auto&&f){const auto t=std::chrono::steady_clock::now();f();legacyKernelSeconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-t).count();};auto timeReal=[&](auto&&f){const auto t=std::chrono::steady_clock::now();f();realZ2KernelSeconds+=std::chrono::duration<double>(std::chrono::steady_clock::now()-t).count();};for(int i=0;i<a.burn;++i){timeLegacy([&](){legacy.rightSweep();});timeReal([&](){q.rightSweep();});audit();timeLegacy([&](){legacy.leftSweep();});timeReal([&](){q.leftSweep();});audit();}
 std::ofstream out(a.csv),old(a.legacy_csv);if(!out||!old)throw std::runtime_error("cannot open output CSV");out<<"measurement,legacy_sign,physical_z2_sign,oracle_z2,legacy_phase_re,legacy_phase_im,diagnostic_phase_re,diagnostic_phase_im,raw_status,raw_trusted,raw_z2,S_pi,S_pi_dq,R_CDW,acceptance,shadow_match,hs_hash,rng_hash,trajectory_hash,green_error\n"<<std::setprecision(17);old<<"measurement,sign,sign_S_pi,sign_S_pi_dq,S_pi,S_pi_dq,R_CDW,acceptance,green_rebuild_relative_error,raw_sign_mismatch\n"<<std::setprecision(17);
 ProjectorRawSignChecks checks,legacyChecks;double zsum=0,lsum=0,spnum=0,dqnum=0,maxphase=0,maxgreen=0;long long accepted=0,attempted=0,oracleMismatch=0,oracleChecks=0,centerOracleMismatch=0,centerOracleChecks=0,diagComparisons=0,legacyDiagMismatch=0;const int nb=std::min(20,a.measurements);std::vector<double>zbin(nb),lbin(nb);std::vector<int>bn(nb);
 for(int k=0;k<a.measurements;++k){PfaffianResult raw;std::string rawName="not_sampled";int rawTrusted=0,rawZ2=0;if(k%a.sign_stride==0){timeReal([&](){raw=q.checkRawSignReadOnly();});checks.record(DataType(q.physicalZ2Sign(),0),raw);PfaffianResult legacyRaw;timeLegacy([&](){legacyRaw=legacy.getSignRawWithStatus();});legacyChecks.record(legacy.sign,legacyRaw);rawName=pfaffianStatusName(raw.status);rawTrusted=raw.ok();if(raw.ok())rawZ2=raw.value.real()>=0?1:-1;}
  const bool doMpSpot=a.mp_spot_stride>0&&k%a.mp_spot_stride==0;auto before0=fields(w0),before1=fields(w1);MatType g0,g1;DataType s0,s1;int zcap=0,captureOracle=0;bool captureOracleUsed=false;timeLegacy([&](){legacy.rightSweep(w0.center,&g0,&s0);});timeReal([&](){q.rightSweep(w1.center,&g1,&s1,&zcap,doMpSpot?&captureOracleUsed:nullptr,doMpSpot?&captureOracle:nullptr);});if(captureOracleUsed){++centerOracleChecks;centerOracleMismatch+=captureOracle!=zcap;}auto after0=fields(w0),after1=fields(w1);accepted+=changes(before1,after1);attempted+=before1.size();audit();if(after0!=after1)shadow=false;
  DataType lp=c0.StructureFactorCDW(g0),ld=c0.StructureFactorCDWOffset(g0),p1=c1.StructureFactorCDW(g1),d1=c1.StructureFactorCDWOffset(g1);double spi=-p1.real(),dq=-d1.real(),ratio=std::abs(spi)>1e-300?1-dq/spi:std::numeric_limits<double>::quiet_NaN();int legacyZ=s0.real()>=0?1:-1;zsum+=zcap;lsum+=legacyZ;spnum+=zcap*spi;dqnum+=zcap*dq;int b=std::min(nb-1,int((static_cast<long long>(k)*nb)/a.measurements));zbin[b]+=zcap;lbin[b]+=legacyZ;++bn[b];maxphase=std::max(maxphase,std::abs(s1.imag()));
  double ge=std::numeric_limits<double>::quiet_NaN();int legacyMismatch=-1;if(a.diagnostic_stride>0&&k%a.diagnostic_stride==0){MatType rebuilt;timeReal([&](){q.rebuildGreenFromFullContourAtBoundary(0,rebuilt);});ge=(q.g-rebuilt).norm()/std::max(rebuilt.norm(),std::numeric_limits<double>::min());maxgreen=std::max(maxgreen,ge);++diagComparisons;MatType rebuilt0;timeLegacy([&](){legacy.rebuildGreenFromFullContourAtBoundary(0,rebuilt0);});PfaffianResult lr;timeLegacy([&](){lr=legacy.getSignRawWithStatus();});if(lr.ok()){legacyMismatch=((legacy.sign.real()>=0)!=(lr.value.real()>=0));legacyDiagMismatch+=legacyMismatch;}}if(doMpSpot){int oz=0;timeReal([&](){oz=oracle(q.op_array);});++q.mp_oracle_adjudication_count;++oracleChecks;oracleMismatch+=oz!=q.physicalZ2Sign();}
  out<<k<<','<<legacyZ<<','<<zcap<<','<<(captureOracleUsed?captureOracle:0)<<','<<s0.real()<<','<<s0.imag()<<','<<s1.real()<<','<<s1.imag()<<','<<rawName<<','<<rawTrusted<<','<<rawZ2<<','<<spi<<','<<dq<<','<<ratio<<','<<(attempted?double(accepted)/attempted:0)<<','<<shadow<<','<<hsHash(w1)<<','<<r1.diagnosticStateHash()<<','<<trajectory<<','<<ge<<'\n';old<<k<<','<<legacyZ<<','<<legacyZ*(-lp.real())<<','<<legacyZ*(-ld.real())<<','<<-lp.real()<<','<<-ld.real()<<','<<(std::abs(lp.real())>1e-300?1-ld.real()/lp.real():std::numeric_limits<double>::quiet_NaN())<<','<<(attempted?double(accepted)/attempted:0)<<','<<ge<<','<<legacyMismatch<<'\n';
  timeLegacy([&](){legacy.leftSweep();});timeReal([&](){q.leftSweep();});audit();if(fields(w0)!=fields(w1))shadow=false;accepted+=changes(after1,fields(w1));attempted+=after1.size();}
 std::vector<double>zb,lb;for(int i=0;i<nb;++i)if(bn[i]){zb.push_back(zbin[i]/bn[i]);lb.push_back(lbin[i]/bn[i]);}const double spi=zsum?spnum/zsum:std::numeric_limits<double>::quiet_NaN(),dq=zsum?dqnum/zsum:std::numeric_limits<double>::quiet_NaN();const auto guard=scaleSafeQRGuardDiagnostics();double runtime=std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();
 std::cout<<std::setprecision(17)<<"{\"status\":\"complete\",\"mode\":\"zero_temperature_projector\",\"L\":"<<a.L<<",\"V\":"<<a.V<<",\"theta\":"<<a.theta<<",\"beta_trial\":"<<a.beta<<",\"dt\":"<<a.dt<<",\"delta\":"<<a.delta<<",\"mu\":"<<a.mu<<",\"boundary\":"<<a.boundary<<",\"hs_scheme\":"<<a.hs<<",\"seed\":"<<a.seed<<",\"burn\":"<<a.burn<<",\"measurements\":"<<a.measurements<<",\"threads\":1,\"average_sign\":"<<zsum/a.measurements<<",\"z2_average_sign\":"<<zsum/a.measurements<<",\"z2_average_sign_err\":"<<sem(zb)<<",\"legacy_average_sign\":"<<lsum/a.measurements<<",\"legacy_average_sign_err\":"<<sem(lb)<<",\"initial_physical_z2\":"<<initialZ2<<",\"initial_raw_status\":\""<<pfaffianStatusName(initialRaw.status)<<"\",\"initial_raw_condition_proxy\":"<<initialRaw.condition_proxy<<",\"initial_raw_phase_reality_error\":"<<initialRaw.phase_reality_error<<",\"S_pi\":"<<spi<<",\"S_pi_dq\":"<<dq<<",\"R_CDW\":"<<(std::isfinite(spi)&&std::abs(spi)>1e-14?1-dq/spi:0)<<",\"acceptance\":"<<(attempted?double(accepted)/attempted:0)<<",\"max_sign_imag\":"<<maxphase<<",\"legacy_complex_phase_max_imag\":"<<q.max_complex_phase_imag<<",\"green_rebuild_comparisons\":"<<diagComparisons<<",\"green_rebuild_relative_error_max\":"<<maxgreen<<",\"mp_spot_stride\":"<<a.mp_spot_stride<<",\"shadow_oracle_z2_comparisons\":"<<oracleChecks<<",\"shadow_oracle_z2_mismatch_count\":"<<oracleMismatch<<",\"center_oracle_z2_comparisons\":"<<centerOracleChecks<<",\"center_oracle_z2_mismatch_count\":"<<centerOracleMismatch<<",\"legacy_raw_mismatch_count\":"<<legacyDiagMismatch<<",\"shadow_trajectory_match\":"<<(shadow?"true":"false")<<",\"trajectory_hash\":"<<trajectory<<",\"final_hs_hash\":"<<hsHash(w1)<<",\"final_rng_hash\":"<<r1.diagnosticStateHash()<<",\"udt_guard_triggers\":"<<guard.trigger_count<<",\"real_z2_initialization_seconds\":"<<realZ2InitializationSeconds<<",\"legacy_kernel_seconds\":"<<legacyKernelSeconds<<",\"real_z2_kernel_seconds\":"<<realZ2KernelSeconds<<",\"real_z2_kernel_overhead_ratio\":"<<(legacyKernelSeconds>0?realZ2KernelSeconds/legacyKernelSeconds:0)<<",\"runtime_seconds\":"<<runtime;projectorJsonRawSignChecks(std::cout,checks);projectorJsonBuildProvenance(std::cout,q);std::cout<<"}\n";if(!shadow||oracleMismatch||centerOracleMismatch)return 3;return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}
